### ISSUE TITLE
Creating The Graph

### ISSUE THREAD

**Issue by ghost** [shihrer/csci446.project1#1]
Hi guys,

As far as the graph goes, it looks like plotting the points is pretty straight forward. After that, plotting lines is going to be a bit harder. I've dug up a divide-and-conquer algorithm I wrote for another class to plot a set of points and find the closest pairs. I think it could be easily modified to find the closest points to a given point. Then all we'd need is to make an algorithm to make sure lines don't intersect.

Let me know what you think.

Chris.

**Comment by ghost** [comment]
After looking over it more, it might actually be easier to start from scratch, as the closest pair algorithm would mostly need to be gutted. I can get us a basic graph working today. Then start working on actually connecting it all together later.

**Comment by shihrer** [comment]
Thanks for getting it setup.  Should remove the IDE specific files and add 'em to the gitignore, though.  We don't need to share that.

**Comment by ghost** [comment]
Came up with the complete graph generator. There shouldn't be any line intersections but I haven't had a chance to actually verify that that is the case. Will see about visually plotting to make sure at another time.
